import React, { FC, ReactNode, useState } from "react";
import Head from "next/head";

type IProps = {
  children?: ReactNode;
};

const AppContainer: FC<IProps> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Ren | Software Developer </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 md:px-20 lg:px-40 bg-white">
        {children}
      </main>
    </div>
  );
};

export default AppContainer;
