import React, { FC, ReactNode, useState } from 'react';
import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';


type IProps = {
  children?: ReactNode;
};

const AppContainer: FC<IProps> = ({ children }) => {
  const [darkMode, setDarkMode] = useState(false);

   // Function will execute on click of button
   const onButtonClick = () => {
    fetch('Resume-Renato-Mission.pdf').then((response) => {
      response.blob().then((blob) => {
        // Creating new object of PDF file
        const fileURL = window.URL.createObjectURL(blob);
        // Setting various property values
        let alink = document.createElement('a');
        alink.href = fileURL;
        alink.download = 'Resume-Renato-Mission.pdf';
        alink.click();
      });
    });
  };

  return (
    <div className={darkMode ? 'dark' : 'bg-slate-100'}>
      <Head>
        <title>Ren Mission Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
      <section className="pt-10 pb-2">
        <nav className="mb-12 flex justify-between">
          <h1 className="text-2xl text-gray-700 font-semibold dark:text-white">
            Ren Mission
          </h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-gray-700 text-2xl dark:text-white"
              />
            </li>
            <li>
              <a
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 font-semibold rounded-md ml-8 "
                href="../public/Resume-Renato-Mission.pdf"
                onClick={onButtonClick}
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
      </section>
        {children}
      </main>
    </div>
  );
};

export default AppContainer;
